### PR TITLE
Fly Mechanic Resolves #353

### LINKED ISSUE #353: Fly Mechanic [Enhancement]
A mechanic that gives a player the ability to fly for an allotted amount of time, with speed being a variable you can set.

This can be replicated with external plugins, but it would be nice to have natively.

### PR DESCRIPTION
**Pull request by RAYCAL2000**
# Changelog
Added a new mechanic known as "Fly". This mechanic allows players to set flight for a duration. Setting flying to false will override any duration and ground the player. Solves Issue #353

## Options
- Flyspeed (Float) - Can only be between the values of -1 and 1. Allows users to set the speed of their flight or upgrade the speed of their light with higher levels.
- Seconds (Double) - How many seconds to allow flight for. The most recent instance of the Fly Mechanic duration is the one that will be used. If Flying is set to False this the duration number is not used.
- Flying (Boolean) - Sets their fly state to either True or False. Mimics creative flight and does not persist when logging out.

### CODE REVIEW

**Comment by Travja** [comment]
It would be good to add a duration option to this so the mechanic will automatically expire after some time so the player isn't left flying potentially indefinitely. Additionally, it would also probably be best to override the `doCleanUp` method to prevent the player from remaining flying when the server shuts down.

**Comment by RAYCAL2000** [comment]
I'll give it a try tomorrow. What's the best way to implement a timer / duration. I looked at some of the other mechanics and saw about 8 different ways to do it.

**Comment by Travja** [comment]
I'd probably do it like it's done in the StatMechanic.

**Comment by RAYCAL2000** [comment]
Should be all set now! I updated the original pull request message to better reflect all the changes now!

**Comment by RAYCAL2000** [comment]
*I lied before...*

I absolutely broke creative flight entirely if the skill is casted or ends when in creative. Should not longer be an issue :)

**Review by Travja — APPROVED** [review]

**Pull request merged**
