### PR TITLE
Fix nested values

### PR DESCRIPTION
**Pull request by funaydmc**
Fix error when curly brackets value inside other curly brackets.

We can use curly brackets to use value in some place.
But when i use command like `execute as @e[nbt={UUID:{targetUUID}}] run say hello`.
The problem here is ProSkillSPI can't resolve value in more than one curly brackets.

### CODE REVIEW

**Comment by fructozer** [comment]
**Here my tests:**
Values: 
- v1 = 1
- v2 = 1234
inputs:
- v1
- {v1}
- {v1} {v2}
- { {v1} - {v2} }
- { {v1} - {v2} }} } { }
- {test} {v1} {v2}} complete

result:
- v1
- 1.0
- 1.0 1234.0
- { 1.0 - 1234.0 }
- { 1.0 - 1234.0 }
- { 1.0 - 1234.0 }} } { }
- {test} 1.0 1234.0} complete

[test script](https://paste.travja.dev/pacaponeco)

**Comment by fructozer** [comment]
maybe we have to remove `.0` subfix automatically when possible

**Comment by Travja** [comment]
Do you know what unit tests are?

**Comment by fructozer** [comment]
no. i don't have experience in it

**Comment by Travja** [comment]
A unit test is basically a small snippet of code designed to test the main code application. It allows us to verify that our methods and things are manipulating data and performing calculations properly. We don't have a ton of unit tests at present, but I'm trying to encourage developers/contributors to add more as they work on the code-base.

See: https://www.baeldung.com/java-unit-testing-best-practices

**Comment by Travja** [comment]
I reworked the logic a little to allow nesting any number of things within each other. There was also an error that would get thrown parsing the double value out of the cast data. I added some unit tests if you want to take a look at those. Assuming this passes testing for your use cases, go ahead and 'Squash and merge' it

**Review by Travja — APPROVED** [review]

**Pull request merged**
