### PR TITLE
update delay mechanic available check

### PR DESCRIPTION
**Pull request by zzz1999**
megre

### CODE REVIEW

**Comment by Travja** [comment]
If I remember correctly, for each skill or each Delay Mechanic block, a new Delay Mechanic is constructed, so it may be possible for the player to have multiple tasks running for a single delay mechanic. That would throw off this code a bit, right?

**Comment by zzz1999** [comment]
I missed it before. 
I made this modification so Developers can terminate the skill immediately and not process the following triggers or mechanics in the remaining skill performance.
A mechanic named AbortSkillMechanic is provided, which can make the caster ignore unexecute triggers or mechanics.

**Comment by zzz1999** [comment]
Could it be merged now?

**Comment by goflishMC** [comment]
> Could it be merged now?

it's the middle of the night for Trav right now.

**Comment by zzz1999** [comment]
> > Could it be merged now?
> 
> it's the middle of the night for Trav right now.

idk , I apology :)

**Comment by zzz1999** [comment]
can this pr be merged?

**Review by Travja — CHANGES_REQUESTED** [review]
This implementation still has issues. When the skill is built, the same DelayMechanic is used whether player 1 or player 2 is casting it. Additionally, player 1 can cast it multiple times. We therefore need to keep track of each invocation of the mechanic for each player. When it is cleaned up, we can cancel all pending tasks. We might also need to add an option to the delay mechanic to cancel uncompleted prior invocations when a new one is fired off. This would allow us to have delays that continue to execute despite the skill being cast again as well as allow us to have "single instance" type skills that can cancel the previous delay before running the new one.

**Comment by zzz1999** [comment]
can this pr be merged?

**Comment by goflishMC** [comment]
> can this pr be merged?

You'll need to address the issues that trav mentioned before it can be merged.

**Comment by zzz1999** [comment]
> > can this pr be merged?
> 
> You'll need to address the issues that trav mentioned before it can be merged.

If I hadn't misunderstood Travja's meaning, I feel I would have addressed the issues in the above three commits.
Guys can create custom triggers to trigger `AbortSkillMechanic ` to pause unexecuted mechanics and triggers.
and players still have this skill, it will execute when cast.
That's a tiny modification. 
I can't get what should I do next in this pull request.

**Review by Travja — APPROVED** [review]

**Pull request merged**
